# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
 paths:
   include:
     - worker/**

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '4c745645-c5f4-488a-a63c-ed2949402c01'
  imageRepository: 'workerapp'
  containerRegistry: 'mhr993.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/worker/Dockerfile'
  tag: '$(Build.BuildId)'
  
  #Variables availabe at DockerFile
  BUILDPLATFORM: 'linux/amd64' #where to build
  TARGETPLATFORM: 'linux/amd64' # For whom to build
  TARGETARCH: 'amd64'

  # Agent VM image name
  #vmImageName: 'ubuntu-latest'

pool:
 name: azureagent

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an Image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
- stage: Push
  displayName: Push Stage
  jobs:
  - job: Push
    displayName: Push
    steps:
    - task: Docker@2
      displayName: Push an image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'
- stage: Update
  displayName: Update K8s Manifest
  jobs:
  - job: Update
    displayName: Update
    steps:
    - task: ShellScript@2
      inputs:
        scriptPath: 'scripts/k8s-manifest-update.sh'
        args: 'worker $(imageRepository) $(tag) $(ACCESS_TOKEN)'
